standard = "2008"
# The preferred case for completions.
preferred_case = "lower"
# File names are either absolute or relative to the parent folder of the vhdl_ls.toml file
[libraries]

# Wildcards and exclude patterns are supported
defaultlib.files = [
    './fw/lib/vhdl/*.vhd',
    './fw/lib/vhdl/*/*.vhd',
    './fw/tb/*/*/*.vhd',
]
